edp:
  name: ""
  version: "epamedp/edp-install:2.2.1"
  additionalToolsTemplate: "additional-tools"
  superAdmins: ""
  admins: ""
  viewers: ""
  dnsWildCard: ""
  storageClass: "gp2"
  devDeploy: "false"
jenkins:
  version: "epamedp/edp-jenkins:2.2.0"
  volumeCapacity: "10Gi"
  stagesVersion: "2.3.0"
  pipelinesVersion: "2.3.0"
adminConsole:
  version: "epamedp/edp-admin-console:2.2.1"
vcs:
  enabled: "false"
  toolName: ""
  groupName: ""
  sshPort: "22"
perf:
  enabled: "false"
  nodeId: ""
  url: ""