# Copyright 2019 EPAM Systems.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

# See the License for the specific language governing permissions and
# limitations under the License.

---
- include_tasks: "{{ platform_type }}.yml"

- name: "Create rolebindings for operators"
  shell: >
    {{ console_tool }} create rolebinding operators-admin-role-to-edp-sa
    --clusterrole=admin
    --serviceaccount={{ operators_deploy_project }}:edp
    --namespace={{ project_cicd }}
  when: "project_cicd not in current_projects_list"

- name: "Looking for shared secrets"
  shell: >
     {{ console_tool }} get secret -n {{ edp_deploy_project }} -o custom-columns=NAME:.metadata.name
     --no-headers=true | grep {{ shared_secrets_mask }}
  register: edp_shared_secrets
  ignore_errors: true
  check_mode: no

- name: "Clone shared secrets to CICD project"
  shell: >
    {{ console_tool }} get --export -o yaml secret {{ item }} -n {{ edp_deploy_project }} |
    oc -n {{ project_cicd }} apply -f - &&
    {{ console_tool }} get --export -o yaml secret {{ item }} -n {{ edp_deploy_project }} |
    sed -e 's/{{ item }}/{{ item | regex_replace(shared_secrets_mask) }}/' |
    oc -n {{ project_cicd }} apply -f -
  with_items:
    - "{{ edp_shared_secrets.stdout_lines }}"

- name: Creates directory for templates
  file:
    path: "{{ templates_dir }}/{{ item }}"
    state: directory
  with_items:
    - "{{ tools.keys() }}"
