global:
  version: "v2.4.0"
  edpName: "edp"
  platform: "openshift"
  dnsWildCard: ""
  admins:
    - "stub_user_one@example.com"
  developers:
    - "stub_user_one@example.com"
    - "stub_user_two@example.com"
  database:
    deploy: true
    image: "postgres:9.6"
    host: "edp-install-wizard-db"
    name: "edp-install-wizard-db"
    port: 5432
    storage:
      class: gp2
      size: 2Gi
  webConsole:
    enabled: true
    url: ""

edp:
  adminGroups:
    - "stub-group-admin"
  developerGroups:
    - "stub-group-developer"

perf:
  enabled: "false"

vcs:
  enabled: "false"

dockerRegistry:
  url: ""

tags:
  keycloak-operator: false
  codebase-operator: false
  jenkins-operator: false
  edp-component-operator: false
  cd-pipeline-operator: false
  nexus-operator: false
  sonar-operator: false
  admin-console-operator: false
  gerrit-operator: false
  reconciler: false

keycloak-operator:
  image:
    name: epamedp/keycloak-operator
    version: v1.4.0
  keycloak:
    url: ""

codebase-operator:
  image:
    name: epamedp/codebase-operator
    version: v2.4.0
  jira:
    integration: false
    name: ""
    apiUrl: ""
    rootUrl: ""
    credentialName: ""

jenkins-operator:
  image:
    name: epamedp/jenkins-operator
    version: v2.4.0
  jenkins:
    deploy: true
    image: epamedp/edp-jenkins
    version: 2.4.0
    storage:
      class: gp2
      size: 10Gi
    initImage:
    libraryPipelinesRepo: "https://github.com/epmd-edp/edp-library-pipelines.git"
    libraryPipelinesVersion: "release-2.5"
    libraryStagesRepo: "https://github.com/epmd-edp/edp-library-stages.git"
    libraryStagesVersion: "release-2.5"
    pullSecrets:
    basePath: ""

cd-pipeline-operator:
  image:
    name: epamedp/cd-pipeline-operator
    version: v2.4.0

nexus-operator:
  image:
    name: epamedp/nexus-operator
    version: v2.4.0
  nexus:
    deploy: true
    name: "nexus"
    image: "sonatype/nexus3"
    version: "3.21.2"
    basePath: ""
    imagePullSecrets:
    storage:
      class: gp2
      size: 10Gi

sonar-operator:
  image:
    name: epamedp/sonar-operator
    version: v2.4.0
  sonar:
    deploy: true
    name: "sonar"
    image: "sonarqube"
    version: "7.9-community"
    initImage: "busybox"
    dbImage: "postgres:9.6"
    storage:
      data:
        class: gp2
        size: 1Gi
      database:
        class: gp2
        size: 1Gi
    imagePullSecrets:
    basePath: ""

admin-console-operator:
  image:
    name: epamedp/admin-console-operator
    version: v2.4.0
  adminConsole:
    image: epamedp/edp-admin-console
    version: 2.4.0
    imagePullSecrets:
    basePath: ""
    testReportTools: "Allure"

gerrit-operator:
  image:
    name: epamedp/gerrit-operator
    version: v2.4.0
  gerrit:
    deploy: true
    name: "gerrit"
    image: "openfrontier/gerrit"
    sshPort: "22"
    version: "3.1.4"
    imagePullSecrets:
    storage:
      size: 1Gi
      class: gp2

reconciler:
  image:
    name: epamedp/reconciler
    version: v2.4.0